<a href="https://colab.research.google.com/github/rhilderbrand/MSDS-422-MachineLearning/blob/main/Hilderbrand_Assignment_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Assignment 6: Neural Networks

This assignment asks you to fit a number of neural networks, comparing processing time and performance across experimental treatments. Processing time will be recorded for the fitting on the train.csv.  Kaggle.com accuracy scores will be reported for all benchmarks

## System Setup & Data Preparation

In [44]:
# prepare for Python version 3 features and functions
from __future__ import division, print_function, unicode_literals

# import common packages
import pandas as pd
import numpy as np
import os

# import TensorFlow
import tensorflow as tf

#suppress tf.logging
import logging
logging.getLogger('tensorflow').disabled = True

# for visualization
%matplotlib inline
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
# split data into train and test sets
(X_train, y_train), (X_test, y_test) = tf.keras.datasets.mnist.load_data()
X_train = X_train.astype(np.float32).reshape(-1, 28*28) / 255.0
X_test = X_test.astype(np.float32).reshape(-1, 28*28) / 255.0
y_train = y_train.astype(np.int32)
y_test = y_test.astype(np.int32)

11493376/11490434 [==============================] - 0s 0us/step


In [6]:
# check data splits for test and train
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(60000, 784)
(10000, 784)
(60000,)
(10000,)


##Model 1 - 2 layers 10 nodes per layer

**Processing Time:** 139 s

**Training Set Accuracy:** 0.8556

**Test Set Accuracy:** 0.8577

In [36]:
%%time
feature_cols = [tf.feature_column.numeric_column("X", shape=[28 * 28])]
dnn_clf_1 = tf.estimator.DNNClassifier(hidden_units=[10,10], n_classes=10,
                                     feature_columns=feature_cols)

input_fn_1 = tf.compat.v1.estimator.inputs.numpy_input_fn(
    x={"X": X_train}, y=y_train, num_epochs=50, batch_size=50, shuffle=True)
dnn_clf_1.train(input_fn=input_fn_1)

CPU times: user 2min 12s, sys: 7.44 s, total: 2min 19s
Wall time: 1min 29s


In [37]:
# evaluate training accuracy
train_1_input_fn = tf.compat.v1.estimator.inputs.numpy_input_fn(
    x={"X": X_train}, y=y_train, shuffle=False)
eval_results_train_1 = dnn_clf_2a.evaluate(input_fn=train_1_input_fn)
eval_results_train_1

{'accuracy': 0.87505,
 'average_loss': 0.44945464,
 'global_step': 120000,
 'loss': 0.44948}

In [38]:
# evalute test accuracy
test_1_input_fn = tf.compat.v1.estimator.inputs.numpy_input_fn(
    x={"X": X_test}, y=y_test, shuffle=False)
eval_results_test_1 = dnn_clf_1.evaluate(input_fn=test_1_input_fn)
eval_results_test_1

{'accuracy': 0.8703,
 'average_loss': 0.47740436,
 'global_step': 60000,
 'loss': 0.47595558}

In [47]:
#confusion matrix for Model 1 predictions
raw_predictions_1 = dnn_clf_1.predict(input_fn=test_1_input_fn)
predictions_1 = [p['class_ids'][0] for p in raw_predictions_1]
confusion_matrix_1 = tf.math.confusion_matrix(y_test, predictions_1)
confusion_matrix_1

<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[ 940,    0,   15,    4,    1,   17,    1,    1,    1,    0],
       [   0, 1097,    0,    7,    3,    4,    4,    1,   19,    0],
       [  20,    1,  832,   26,   32,   28,   25,   13,   51,    4],
       [   4,    1,   22,  864,    4,   61,    4,   28,   14,    8],
       [   3,    8,   16,    0,  873,    0,    9,    2,   18,   53],
       [   9,   10,   16,   69,   11,  674,   11,   12,   68,   12],
       [  26,    2,   27,    4,   19,   11,  847,    0,   22,    0],
       [   1,   18,   24,   12,   19,    3,    0,  893,    5,   53],
       [  11,    5,   14,   13,   13,   43,   14,   13,  826,   22],
       [   8,   24,    5,   11,   53,   12,    0,   32,    7,  857]],
      dtype=int32)>

In [ ]:
# https://medium.com/@dtuk81/confusion-matrix-visualization-fc31e3f30fea
sns.heatmap(confusion_matrix_1, annot=True)

##Model 2 - 2 layers 20 nodes per layer

**Processing Time:** 137 s

**Training Set Accuracy:** 0.1141

**Test Set Accuracy:** 0.1113

In [25]:
%%time
feature_cols = [tf.feature_column.numeric_column("X", shape=[28 * 28])]
dnn_clf_2 = tf.estimator.DNNClassifier(hidden_units=[20,20], n_classes=10,
                                     feature_columns=feature_cols)

input_fn_2 = tf.compat.v1.estimator.inputs.numpy_input_fn(
    x={"X": X_train}, y=y_train, num_epochs=50, batch_size=50, shuffle=True)
dnn_clf_2a.train(input_fn=input_fn_2)

CPU times: user 2min 10s, sys: 7.31 s, total: 2min 17s
Wall time: 1min 28s


In [27]:
# evaluate training accuracy
train_2_input_fn = tf.compat.v1.estimator.inputs.numpy_input_fn(
    x={"X": X_train}, y=y_train, shuffle=False)
eval_results_train_2 = dnn_clf_2.evaluate(input_fn=train_2_input_fn)
eval_results_train_2

{'accuracy': 0.11411667,
 'average_loss': 2.3547013,
 'global_step': 0,
 'loss': 2.3547351}

In [28]:
# evalute test accuracy
test_2_input_fn = tf.compat.v1.estimator.inputs.numpy_input_fn(
    x={"X": X_test}, y=y_test, shuffle=False)
eval_results_test_2 = dnn_clf_2.evaluate(input_fn=test_2_input_fn)
eval_results_test_2

{'accuracy': 0.1113,
 'average_loss': 2.3078558,
 'global_step': 0,
 'loss': 2.3081474}

In [41]:
#confusion matrix for Model 2 predictions
raw_predictions_2 = dnn_clf_2.predict(input_fn=test_2_input_fn)
predictions_2 = [p['class_ids'][0] for p in raw_predictions_2]
confusion_matrix_2 = tf.math.confusion_matrix(y_test, predictions_2)
confusion_matrix_2

<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[637,   0,   7, 281,  10,   0,   0,   0,  12,  33],
       [432,   2, 466, 158,  57,   0,   0,   0,   2,  18],
       [476,   0,   8, 484,  37,   0,   0,   0,   2,  25],
       [593,   0,  23, 278,   0,   0,   0,   2,   1, 113],
       [712,   1,  15, 185,  30,   0,   0,   0,   0,  39],
       [540,   0,  16, 200,   5,   0,   0,   0,   2, 129],
       [482,   0,   3, 456,   7,   0,   0,   0,   1,   9],
       [645,   0,  88, 275,   1,   0,   0,   4,   0,  15],
       [598,   0,  18, 273,  44,   0,   0,   0,   3,  38],
       [693,   0,  46, 211,  27,   0,   0,   1,   0,  31]], dtype=int32)>

##Model 3 - 5 layers 10 nodes per layer

**Processing Time:** 147 s

**Training Set Accuracy:** 0.77805

**Test Set Accuracy:** 0.785

In [29]:
%%time
feature_cols = [tf.feature_column.numeric_column("X", shape=[28 * 28])]
dnn_clf_3 = tf.estimator.DNNClassifier(hidden_units=[10,10,10,10,10], n_classes=10,
                                     feature_columns=feature_cols)

input_fn_3 = tf.compat.v1.estimator.inputs.numpy_input_fn(
    x={"X": X_train}, y=y_train, num_epochs=50, batch_size=50, shuffle=True)
dnn_clf_3.train(input_fn=input_fn_3)

CPU times: user 2min 20s, sys: 7.06 s, total: 2min 27s
Wall time: 1min 33s


In [30]:
# evaluate training accuracy
train_3_input_fn = tf.compat.v1.estimator.inputs.numpy_input_fn(
    x={"X": X_train}, y=y_train, shuffle=False)
eval_results_train_3 = dnn_clf_3.evaluate(input_fn=train_3_input_fn)
eval_results_train_3

{'accuracy': 0.77805,
 'average_loss': 0.7034688,
 'global_step': 60000,
 'loss': 0.7035184}

In [31]:
# evalute test accuracy
test_3_input_fn = tf.compat.v1.estimator.inputs.numpy_input_fn(
    x={"X": X_test}, y=y_test, shuffle=False)
eval_results_test_3 = dnn_clf_3.evaluate(input_fn=test_3_input_fn)
eval_results_test_3

{'accuracy': 0.785,
 'average_loss': 0.69971293,
 'global_step': 60000,
 'loss': 0.69918656}

In [42]:
#confusion matrix for Model 3 predictions
raw_predictions_3 = dnn_clf_3.predict(input_fn=test_3_input_fn)
predictions_3 = [p['class_ids'][0] for p in raw_predictions_3]
confusion_matrix_3 = tf.math.confusion_matrix(y_test, predictions_3)
confusion_matrix_3

<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[ 917,    0,    1,   31,    0,    7,   19,    4,    1,    0],
       [   0, 1048,   71,    2,    4,    3,    5,    0,    0,    2],
       [   9,   39,  760,   23,   33,   37,   33,    5,   72,   21],
       [  21,    1,   14,  744,    0,  142,    3,   20,   39,   26],
       [   0,   10,   36,    0,  812,    0,    8,    1,   22,   93],
       [  12,    1,   21,  241,    7,  428,   26,    7,  117,   32],
       [  12,   16,   45,    1,    3,   11,  867,    0,    0,    3],
       [   2,    7,   17,    2,   15,    0,    0,  843,    2,  140],
       [   3,    3,   99,   38,   22,   62,    4,    1,  702,   40],
       [   5,    1,    4,   21,  175,    3,    3,   61,    7,  729]],
      dtype=int32)>

##Model 4 - 5 layers 20 nodes per layer

**Processing Time:** 156 s

**Training Set Accuracy:** 0.89856

**Test Set Accuracy:** 0.8995

In [32]:
%%time
feature_cols = [tf.feature_column.numeric_column("X", shape=[28 * 28])]
dnn_clf_4 = tf.estimator.DNNClassifier(hidden_units=[20,20,20,20,20], n_classes=10,
                                     feature_columns=feature_cols)

input_fn_4 = tf.compat.v1.estimator.inputs.numpy_input_fn(
    x={"X": X_train}, y=y_train, num_epochs=50, batch_size=50, shuffle=True)
dnn_clf_4.train(input_fn=input_fn_4)

CPU times: user 2min 29s, sys: 7.34 s, total: 2min 36s
Wall time: 1min 42s


In [33]:
# evaluate training accuracy
train_4_input_fn = tf.compat.v1.estimator.inputs.numpy_input_fn(
    x={"X": X_train}, y=y_train, shuffle=False)
eval_results_train_4 = dnn_clf_4.evaluate(input_fn=train_4_input_fn)
eval_results_train_4

{'accuracy': 0.89856666,
 'average_loss': 0.35551164,
 'global_step': 60000,
 'loss': 0.35555896}

In [34]:
# evalute test accuracy
test_4_input_fn = tf.compat.v1.estimator.inputs.numpy_input_fn(
    x={"X": X_test}, y=y_test, shuffle=False)
eval_results_test_4 = dnn_clf_4.evaluate(input_fn=test_4_input_fn)
eval_results_test_4

{'accuracy': 0.8995,
 'average_loss': 0.34878668,
 'global_step': 60000,
 'loss': 0.34688634}

In [43]:
#confusion matrix for Model 4 predictions
raw_predictions_4 = dnn_clf_4.predict(input_fn=test_4_input_fn)
predictions_4 = [p['class_ids'][0] for p in raw_predictions_4]
confusion_matrix_4 = tf.math.confusion_matrix(y_test, predictions_4)
confusion_matrix_4

<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[ 947,    0,    3,    1,    5,   14,    8,    1,    1,    0],
       [   0, 1104,   11,    3,    0,    0,    2,    2,   13,    0],
       [  11,   18,  897,   25,   10,    5,   25,   15,   23,    3],
       [   4,    2,   22,  910,    0,   29,    0,   12,   25,    6],
       [   1,    0,    7,    0,  884,    2,   12,    2,   11,   63],
       [  23,    1,   12,   77,   15,  701,   12,    7,   33,   11],
       [  24,    2,   16,    0,   10,    8,  893,    0,    5,    0],
       [   3,   21,   22,    3,    6,    1,    0,  935,    3,   34],
       [   5,   12,    8,   36,    8,   42,   12,    3,  822,   26],
       [   6,    4,    2,    6,   40,   17,    1,   22,    9,  902]],
      dtype=int32)>

##Summary